### PR TITLE
Replace hashlib with crypto

### PR DESCRIPTION
**Pull request by deepwell**
Removed the requirement for hashlib because it no longer works well on node 0.6.

### CODE REVIEW

**Comment by deepwell** [comment]
Or another idea is to depend on hashlib2: https://github.com/karlseguin/hashlib/

**Comment by pspeter3** [comment]
Any chance of this ever getting pulled in?

**Comment by NodePing** [comment]
Please pull this in.

**Comment by michielbdejong** [comment]
+1

cc @ditesh

**Pull request closed without merging**
